spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:db/migration/V1__init.sql
  application:
    name: processor-svc
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: telemetry-processor
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  datasource:
    url: jdbc:postgresql://${DB_HOST:securemw}:${DB_PORT:5432}/${DB_NAME:securemw}
    username: ${DB_USER:securemw}
    password: ${DB_PASS:securemw}
    driver-class-name: org.postgresql.Driver
    hikari:
      # facoltativo: evita il fail-fast se il DB ritarda ad avviarsi in locale
      initialization-fail-timeout: 0

server:
  port: 8082

app:
  topics:
    telemetry: telemetry.v1
    dlq: telemetry.dlq
  security:
    aesKeyB64: ${AES_KEY_B64}
    hmacKeyB64: ${HMAC_KEY_B64}

logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.springframework.jdbc.datasource: DEBUG


    # PROCESSOR
